name: Publish
on:
    push:
        branches-ignore:
            - "*"
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            - uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Install package and publish via lerna
              run: |
                  npm ci
                  npm run build
                  npx lerna publish from-git --no-push --force-publish=* --yes --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
